module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        container: {
            center: true,
            padding: "0",
        },
        screens: {
            sm: "640px",
            md: "768px",
            lg: "948px",
            xl: "1188px",
            "2xl": "1450px",
        },
        extend: {
            colors: {
                // Primary color and feedback colors
                primary: {
                    25: "rgb(var(--primary-25))",
                    50: "rgb(var(--primary-50))",
                    75: "rgb(var(--primary-75))",
                    100: "rgb(var(--primary-100))",
                    150: "rgb(var(--primary-150))",
                    200: "rgb(var(--primary-200))",
                    250: "rgb(var(--primary-250))",
                    300: "rgb(var(--primary-300))",
                    350: "rgb(var(--primary-350))",
                    400: "rgb(var(--primary-400))",
                    450: "rgb(var(--primary-450))",
                    500: "rgb(var(--primary-500))",
                    550: "rgb(var(--primary-550))",
                    600: "rgb(var(--primary-600))",
                    650: "rgb(var(--primary-650))",
                    700: "rgb(var(--primary-700))",
                    750: "rgb(var(--primary-750))",
                    800: "rgb(var(--primary-800))",
                    850: "rgb(var(--primary-850))",
                    900: "rgb(var(--primary-900))",
                },

                secondary: {
                    25: "rgb(var(--primary-25))",
                    50: "rgb(var(--primary-50))",
                    75: "rgb(var(--primary-75))",
                    100: "rgb(var(--primary-100))",
                    150: "rgb(var(--primary-150))",
                    200: "rgb(var(--primary-200))",
                    250: "rgb(var(--primary-250))",
                    300: "rgb(var(--primary-300))",
                    350: "rgb(var(--primary-350))",
                    400: "rgb(var(--primary-400))",
                    450: "rgb(var(--primary-450))",
                    500: "rgb(var(--primary-500))",
                    550: "rgb(var(--primary-550))",
                    600: "rgb(var(--primary-600))",
                    650: "rgb(var(--primary-650))",
                    700: "rgb(var(--primary-700))",
                    750: "rgb(var(--primary-750))",
                    800: "rgb(var(--primary-800))",
                    850: "rgb(var(--primary-850))",
                    900: "rgb(var(--primary-900))",
                },

                danger: {
                    25: "rgb(var(--danger-25))",
                    50: "rgb(var(--danger-50))",
                    75: "rgb(var(--danger-75))",
                    100: "rgb(var(--danger-100))",
                    150: "rgb(var(--danger-150))",
                    200: "rgb(var(--danger-200))",
                    250: "rgb(var(--danger-250))",
                    300: "rgb(var(--danger-300))",
                    350: "rgb(var(--danger-350))",
                    400: "rgb(var(--danger-400))",
                    450: "rgb(var(--danger-450))",
                    500: "rgb(var(--danger-500))",
                    550: "rgb(var(--danger-550))",
                    600: "rgb(var(--danger-600))",
                    650: "rgb(var(--danger-650))",
                    700: "rgb(var(--danger-700))",
                    750: "rgb(var(--danger-750))",
                    800: "rgb(var(--danger-800))",
                    850: "rgb(var(--danger-850))",
                    900: "rgb(var(--danger-900))",
                },

                warning: {
                    25: "rgb(var(--warning-25))",
                    50: "rgb(var(--warning-50))",
                    75: "rgb(var(--warning-75))",
                    100: "rgb(var(--warning-100))",
                    150: "rgb(var(--warning-150))",
                    200: "rgb(var(--warning-200))",
                    250: "rgb(var(--warning-250))",
                    300: "rgb(var(--warning-300))",
                    350: "rgb(var(--warning-350))",
                    400: "rgb(var(--warning-400))",
                    450: "rgb(var(--warning-450))",
                    500: "rgb(var(--warning-500))",
                    550: "rgb(var(--warning-550))",
                    600: "rgb(var(--warning-600))",
                    650: "rgb(var(--warning-650))",
                    700: "rgb(var(--warning-700))",
                    750: "rgb(var(--warning-750))",
                    800: "rgb(var(--warning-800))",
                    850: "rgb(var(--warning-850))",
                    900: "rgb(var(--warning-900))",
                },

                success: {
                    25: "rgb(var(--success-25))",
                    50: "rgb(var(--success-50))",
                    75: "rgb(var(--success-75))",
                    100: "rgb(var(--success-100))",
                    150: "rgb(var(--success-150))",
                    200: "rgb(var(--success-200))",
                    250: "rgb(var(--success-250))",
                    300: "rgb(var(--success-300))",
                    350: "rgb(var(--success-350))",
                    400: "rgb(var(--success-400))",
                    450: "rgb(var(--success-450))",
                    500: "rgb(var(--success-500))",
                    550: "rgb(var(--success-550))",
                    600: "rgb(var(--success-600))",
                    650: "rgb(var(--success-650))",
                    700: "rgb(var(--success-700))",
                    750: "rgb(var(--success-750))",
                    800: "rgb(var(--success-800))",
                    850: "rgb(var(--success-850))",
                    900: "rgb(var(--success-900))",
                },

                info: {
                    25: "rgb(var(--info-25))",
                    50: "rgb(var(--info-50))",
                    75: "rgb(var(--info-75))",
                    100: "rgb(var(--info-100))",
                    150: "rgb(var(--info-150))",
                    200: "rgb(var(--info-200))",
                    250: "rgb(var(--info-250))",
                    300: "rgb(var(--info-300))",
                    350: "rgb(var(--info-350))",
                    400: "rgb(var(--info-400))",
                    450: "rgb(var(--info-450))",
                    500: "rgb(var(--info-500))",
                    550: "rgb(var(--info-550))",
                    600: "rgb(var(--info-600))",
                    650: "rgb(var(--info-650))",
                    700: "rgb(var(--info-700))",
                    750: "rgb(var(--info-750))",
                    800: "rgb(var(--info-800))",
                    850: "rgb(var(--info-850))",
                    900: "rgb(var(--info-900))",
                },

                // Background colors
                background: {
                    primary: "rgb(var(--background-primary))",
                    secondary: "rgb(var(--background-secondary))",
                    tertiary: "rgb(var(--background-tertiary))",
                },

                // Text colors
                foreground: {
                    primary: "rgb(var(--foreground-primary))",
                    secondary: "rgb(var(--foreground-secondary))",
                    tertiary: "rgb(var(--foreground-tertiary))",
                },

                // Accent
                accent: {
                    light: "rgb(var(--accent-light))",
                    medium: "rgb(var(--accent-medium))",
                    dark: "rgb(var(--accent-dark))",
                },

                table: {
                    header: "rgb(var(--table-header))",
                },

                border: "rgb(var(--border))",
            },
            boxShadow: {
                shadow: "0 0 24px 0 rgba(6, 23, 53, 0.15)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}
